# Generated by Django 3.0.3 on 2020-03-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
