# Generated by Django 3.0.3 on 2020-04-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('com', 'committees'), ('intd', 'Intern Diaries'), ('als', 'Alumsays'), ('compe', 'competitive exams'), ('sos', 'sound of silence')], max_length=50),
        ),
    ]
