# Generated by Django 3.0.3 on 2020-04-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200403_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('cmp', 'campus'), ('intd', 'Intern Diaries'), ('als', 'Alumsays'), ('compe', 'competetive exams'), ('sos', 'sound of silence')], max_length=50),
        ),
    ]
