# Generated by Django 3.0.3 on 2020-04-17 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
