# Generated by Django 3.0.3 on 2020-05-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearbookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('regno', models.IntegerField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('aboutme', models.TextField()),
                ('wdysy', models.TextField()),
                ('links', models.TextField()),
                ('souvenir', models.ImageField(upload_to='images/yearbook_souvenirs/')),
                ('photo', models.ImageField(upload_to='images/yearbook_photos/')),
            ],
        ),
    ]
