# Generated by Django 3.0.3 on 2020-06-18 16:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookdata',
            name='aboutme',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AddField(
            model_name='yearbookdata',
            name='branch',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='yearbookdata',
            name='coverphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/yearbook_photos/'),
        ),
        migrations.AddField(
            model_name='yearbookdata',
            name='links',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearbookdata',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='yearbookdata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/yearbook_photos/'),
        ),
        migrations.AddField(
            model_name='yearbookdata',
            name='regno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='yearbookdata',
            name='souvenir',
            field=models.ImageField(blank=True, null=True, upload_to='images/yearbook_souvenirs/'),
        ),
        migrations.AddField(
            model_name='yearbookdata',
            name='yfm',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearbookdata',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
