# Generated by Django 3.0.3 on 2020-05-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookdata',
            name='regno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yearbookdata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
