# Generated by Django 3.0.3 on 2020-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookdata',
            name='coverphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/yearbook_photos/'),
        ),
    ]
