# Generated by Django 3.0.3 on 2020-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_auto_20200523_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookdata',
            name='branch',
            field=models.CharField(default='Branch', max_length=50),
        ),
    ]
