# Generated by Django 3.0.3 on 2020-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0003_yearbookdata_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookdata',
            name='coverphoto',
            field=models.ImageField(null=True, upload_to='images/yearbook_photos'),
        ),
    ]
