# Generated by Django 3.0.3 on 2020-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0004_yearbookdata_coverphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookdata',
            name='wdysy',
            field=models.TextField(null=True),
        ),
    ]
