# Generated by Django 3.0.3 on 2020-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0005_auto_20200613_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookdata',
            name='yfm',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='yearbookdata',
            name='links',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='yearbookdata',
            name='souvenir',
            field=models.ImageField(null=True, upload_to='images/yearbook_souvenirs/'),
        ),
    ]
