# Generated by Django 3.0.3 on 2020-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0007_auto_20200613_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookdata',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
