# Generated by Django 3.0.3 on 2020-06-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0008_auto_20200613_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearbookdata',
            name='photo',
        ),
    ]
