# Generated by Django 3.0.3 on 2020-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0009_remove_yearbookdata_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookdata',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/yearbook_photos/'),
        ),
        migrations.AlterField(
            model_name='yearbookdata',
            name='coverphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/yearbook_photos/'),
        ),
    ]
