# Generated by Django 3.0.3 on 2020-06-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0010_auto_20200615_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookdata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/yearbook_photos/'),
        ),
    ]
