# Generated by Django 3.0.3 on 2020-06-15 20:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0011_auto_20200615_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookdata',
            name='wdysy',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='yearbookdata',
            name='yfm',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
